language: objective-c
osx_image: xcode9.4
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install:
- pod repo update
- pod install
- gem install xcpretty -N
script:
- xcodebuild -workspace AudioKitSynthOne.xcworkspace -scheme AudioKitSynthOne -sdk iphonesimulator | xcpretty
